### PR TITLE
Bugfix/Lifecycle fixes

### LINKED ISSUE #541: App lifecycle issues
When exiting the app with back button and opening again (and in other cases when the host Activity is recreated), we should properly release old views and anchors and then re-create them to prevent memory leaks. This issue is related to #6.

### PR DESCRIPTION
**Pull request by darek607**
closes #541

Also:
- fixed the big lag after reloading an app in React Native,
- utilizing `onUpdate` function instead of `Handler.postDelayed` for easier management when app is in background (our current Nodes implementation does no longer require rebuild / layout loops that happen before onUpdate)
- other minor bug fixes

### CODE REVIEW

File: android/src/main/java/com/magicleap/magicscript/ArFragmentContainer.kt [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+                addFragment(fragment, tag)
+                // since we wait until next frame, we have to layout view manually
+                layoutFragmentView()
+            }
+        }
+
+    }
+
+    fun dropFragment(tag: String) {
+        logMessage("dropFragment")
```
Comment (grzegorzdec) [inline android/src/main/java/com/magicleap/magicscript/ArFragmentContainer.kt:83]: useless?

File: android/src/main/java/com/magicleap/magicscript/scene/UiNodesManager.kt [hunk 2]
```diff
@@ -97,12 +99,14 @@ class UiNodesManager : NodesManager, LifecycleEventListener {
 
     @Synchronized
     override fun clear() {
-        logMessage("clear")
-        nodesById.forEach { (_, node) ->
-            detachNode(node)
-            node.onDestroy()
+        Handler(Looper.getMainLooper()).post {
+            logMessage("clear, nodeCount = ${nodesById.size}")
```
Comment (grzegorzdec) [inline android/src/main/java/com/magicleap/magicscript/scene/UiNodesManager.kt:103]: useless?
