### PR TITLE
Improve/#294 layout fixes

### LINKED ISSUE #294: iOS bugs
- [ ] ~**scrollBar** - clarify how to handle vertical scroll bar (should we manually rotate it or automate it?)~ (moved to #537)
- [x] **toggleGroup** - toggles are not visible when "innerLayout" mode is off
- [x] **rectLayout** - analyze this scene and make sure it behaves correctly 
- [x] **scrollView** - when changing alignment, the content's behavior is weird
- [x] **toggle** - alignment/layout does not work properly
- [x] **slider** flickers while changing value
- [x] all **listViewItems** should have the same width for vertical orientation (height for horizontal orientation)
- [x] **dialog** - make sure the dialog's background stops the touch events

### PR DESCRIPTION
**Pull request by pleszkiewicz**
#294

### CODE REVIEW

File: ios/RNMagicScript/components/UiNodesManager.swift [hunk 1]
```diff
@@ -196,16 +196,22 @@ import SceneKit
...
-            updateLayoutFor(node: child)
+            enumeratePostOrder(node: child, block: block)
         }
-        
+
         if let transformNode = node as? TransformNode {
-            transformNode.layoutIfNeeded()
+            block(transformNode)
         }
     }
```
Comment (SPaluchiewiczSofomo) [inline ios/RNMagicScript/components/UiNodesManager.swift]: I just wonder if this can be extension to `SCNNode` or `TransformNode`?
